# Generated by Django 3.2 on 2024-02-17 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_users', '0008_alter_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='confirmation_code',
        ),
    ]
