# Generated by Django 3.2 on 2024-02-19 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_users', '0012_auto_20240218_1522'),
        ('api_users', '0012_auto_20240218_2145'),
    ]

    operations = [
    ]
