# Generated by Django 3.2 on 2024-02-19 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_auto_20240218_1522'),
        ('reviews', '0009_auto_20240219_0115'),
    ]

    operations = [
    ]
