# Generated by Django 3.2 on 2024-02-19 09:25

from django.db import migrations, models
import reviews.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_merge_0008_auto_20240218_1522_0009_auto_20240219_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveSmallIntegerField(db_index=True, validators=[reviews.validators.year_validator], verbose_name='Год'),
        ),
    ]
